version: '3'

services:
  devtech-backend:
    container_name: devtech-backend
    build: '.'
    volumes:
      - .:/home/node/backend
      - /home/node/backend/node_modules
    depends_on:
      - postgres-devtech
    networks:
      - app-connect
    ports:
      - '3333:3333'

  postgres-devtech:
    container_name: postgres-devtech
    image: postgres:11
    restart: unless-stopped
    volumes:
      - postgres-devtech-data:/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-connect

volumes:
  postgres-devtech-data:

networks:
  app-connect:
    driver: bridge
